<?php

namespace GameBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findByUser(User $user)
    {
        $ugs = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('IDENTITY(ug.purchaseContact), IDENTITY(ug.saleContact)')
            ->from('GameBundle:UserGame', 'ug')
            ->where('ug.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();

        $contactIds = [];
        foreach ($ugs as $ug) {
            $contactIds[] = $ug[1];
            $contactIds[] = $ug[2];
        }

        $contactIds = array_unique($contactIds);
        return $this->findBy([
            'id' => $contactIds
        ]);
    }
}
