<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function countAll()
    {
        return
            (int)
            $this->createQueryBuilder('g')
                ->select('count(g.id)')
                ->getQuery()
                ->getSingleScalarResult();
    }

    public function countByIgdbUpdate($igdbUpdate)
    {
        return
            (int)
            $this->createQueryBuilder('g')
                ->select('count(g.id)')
                ->where('g.igdbUpdate = :igdbUpdate')
                ->setParameter('igdbUpdate', $igdbUpdate)
                ->getQuery()
                ->getSingleScalarResult();
    }

    public function findUserGameByIgdbId(User $user, $igdbId)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ug')
            ->from('GameBundle:UserGame', 'ug')
            ->innerJoin('ug.game', 'g')
            ->where('ug.user = :user')
            ->andWhere('g.igdbId = :igdb_id')
            ->setParameter('user', $user)
            ->setParameter('igdb_id', $igdbId)
            ->getQuery()
            ->getResult();
    }
}
