<?php

namespace GameBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameRepository extends EntityRepository
{
    public function countByUser(User $user)
    {
        return
            (int)
            $this->createQueryBuilder('ug')
                ->select('count(ug.game)')
                ->where('ug.user = :user')
                ->setParameter('user', $user)
                ->getQuery()
                ->getSingleScalarResult();
    }
}
