<?php

namespace GameBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameRepository extends EntityRepository
{
    public function countByUser($user)
    {
        return 10;

//        return
//            (int)
//            $this->createQueryBuilder('ug')
//                ->select('count(ug.game)')
//                ->where('ug.user = :user')
//                ->setParameter('user', $user)
//                ->getQuery()
//                ->getSingleScalarResult();
    }

    public function userPlaces(User $user)
    {
        $results = $this->createQueryBuilder('ug')
            ->select('ug.purchasePlace, ug.salePlace')
            ->where('ug.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();

        $places = [];

        foreach ($results as $ug) {
            if (!is_null($ug['purchasePlace']) && !empty($ug['purchasePlace'])) {
                $places[] = $ug['purchasePlace'];
            }
            if (!is_null($ug['salePlace']) && !empty($ug['salePlace'])) {
                $places[] = $ug['salePlace'];
            }
        }


        return array_values(array_unique($places));
    }
}
