game:
    resource: "@GameBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    host:     '%admin_host%'

_sonata_admin:
    resource: .
    type:     sonata_admin

api_game:
    resource: "@GameBundle/Controller"
    type:     rest
    host:     '%game_api_host%'

user:
    resource: "@UserBundle/Controller"
    type:     rest
    host:     '%game_api_host%'