# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    igdb:
        class: GameBundle\Services\IGDB
        arguments:
          $igdbKey: '%igdb_key%'

    my_success_handler:
        class: UserBundle\Security\AuthenticationSuccessHandler
        arguments: ['@lexik_jwt_authentication.jwt_manager', '@event_dispatcher']
        tags:
            - { name: 'monolog.logger', channel: 'security' }


    palma_api.event.jwt_created_listener:
          class: UserBundle\EventListener\JWTCreatedListener
          arguments: [ '@request_stack' ]
          tags:
              - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
